### ISSUE TITLE
[Bug] Deep Dungeons breaks toolbars

### ISSUE THREAD

**Issue by alexpado** [una-xiv/umbra#280]
When disabling/enabling or restarting Umbra in a deep dungeon, toolbars do not come back.

Here is the relevant logs:
```
Exception during raise of "Void OnUmbraDraw()"
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.InvalidOperationException: Zone not initialized
       at Umbra.Game.ZoneManager.get_CurrentZone() in C:\Users\Shadow\source\repos\umbra\Umbra.Game\src\Zone\ZoneManager.cs:line 36
       at Umbra.Markers.System.WorldMarkerRegistry.GetMarkers() in C:\Users\Shadow\source\repos\umbra\Umbra\src\Markers\System\WorldMarkerRegistry.cs:line 57
       at Umbra.Markers.System.Renderer.WorldMarkerRenderer.GetMarkersToRender() in C:\Users\Shadow\source\repos\umbra\Umbra\src\Markers\System\Renderer\WorldMarkerRenderer.cs:line 117
       at Umbra.Markers.System.Renderer.WorldMarkerRenderer.OnDraw() in C:\Users\Shadow\source\repos\umbra\Umbra\src\Markers\System\Renderer\WorldMarkerRenderer.cs:line 80
       at InvokeStub_WorldMarkerRenderer.OnDraw(Object, Object, IntPtr*)
       at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
       --- End of inner exception stack trace ---
       at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
       at Umbra.Common.Scheduler.DrawHandler.Invoke() in C:\Users\Shadow\source\repos\umbra\Umbra.Common\src\Scheduler\Scheduler.cs:line 218
       at Umbra.Common.Scheduler.OnUmbraDraw() in C:\Users\Shadow\source\repos\umbra\Umbra.Common\src\Scheduler\Scheduler.cs:line 93
       at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

After few initial checks in `ZoneManager`, here's my first wild guess:

Deep Dungeons do not have a mini-map available, hence, `clientState.MapId` may be set to `0`. This in term exit early `OnTick()` without setting `_zone`, causing the exception when `CurrentZone` is accessed.

Tested on PotD and HoH (not on EO, but safe to assume this will also happen)

**Comment by GayPotatoEmma** [comment]
This same issue also seems to prevent the functionality of several widgets in the event that you don't reload the bar.

Confirmed widgets:
- Coordinates
- Location
- Weather

**Comment by haroldiedema** [comment]
This can be fixed easily in places where `.CurrentZone` is accessed by adding a check before it on `ZoneManager.HasCurrentZone`. If this is `false`, just return early from the tick/draw methods.
